---
title: "deberR"
author: "Damaris"
date: "26/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# CREAR UN IDENTIFICADOR 
```{r}
ciudad <- "Latacunga"
print (ciudad)
```
```{r}
paises_andes <- c("Argentina", "Bolivia", "Chile", "Brasil", "Colombia", "Ecuador", "Peru", "Venezuela")
print (paises_andes)
```
```{r}
# crear un data frame con doce eventos 
nombres = c("Martin","Jose","Irene","Wendy","Sofia","Rolando","Elias","Pamela","Rocio","Joao","Joan","Lucia")
edad = c(29,33,22,46,12,18,54,20,15,70,80,17)
estatura_cm =c(1.80,1.67,1.56,1.59,1.50,1.75,1.78,1.56,1.90,1.45,1.56,1.67)
genero = c("masculino","masculino","femenino","femenino","femenino","masculino","masculino","femenino","femenino","masculino","masculino","femenino")
frutafavorita = c("mango","fresa","uva","fresa","banano","fresa","fresa","sandia","fresa","melon","fresa","mandarina")
cerouno = c("0","0","1","1","1","0","0","1","1","0","0","1")
 dataf = data.frame(nombres,edad,estatura_cm,genero,frutafavorita,cerouno)
 dataf
 
```

```{r}
print(head(DNase,176))
# concentracion entre 0.1 & 0.2
a=subset(DNase, conc >= 0.1 & conc <= 0.2)
print(a)
# Run diferente de 2 & concentracion mayor a 0.2 y densidad menor o igual a 1
dos=subset(DNase,  Run!=2 & conc > 0.2 & density <= 1 )
print(dos)
```
```{r}
#install.packages("dplyr")
#library(dplyr)
#a=data.frame(DNase)
#concentracion entre 0.1 & 0.2
#b= filter(a, conc > 0.1 & conc < 0.2)
#View(b)
#b
#Run diferente de 2 & concentracion mayor a 0.2 y densidad menor o igual a 1
#dos= filter(a, Run!=2 & conc > 0.2 & density <= 1)
#View(dos)
#dos

```





Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
